name: Deploy Yuque-Hexo Public To Pages

on:
  push:
    branches:
      - main 
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: 获取最新代码
        run: |
          git fetch --all
          git pull origin master

      - name: 安装node环境
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: 使用elog
        run: |
          export TZ='Asia/Shanghai'
          pnpm install --no-frozen-lockfile
           # 安装glob的类型定义
          pnpm add -D @types/glob
          pnpm run build 

      - name: 拉取语雀文章
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
          ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          node packages/cli/bin/elog.js sync

      - name: 复制文件并提交
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git status  # 显示更改状态
          git commit -m "docs(yuque): update posts from Yuque" || echo "没有更改需要提交"
          git push || echo "推送失败，请检查权限和远程仓库状态"
        env:
          GIT_TRACE: 1  # 启用 Git 跟踪以获取更多信息

      - name: 检出目标仓库
        uses: actions/checkout@v2
        with:
          repository: gyc-12/gyc-hexo
          token: ${{ secrets.ACCESS_TOKEN }}
          path: gyc-hexo
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: 更新目标仓库并复制文件
        run: |
          cd gyc-hexo
          git fetch --all
          git pull origin main
          cd ..
          cp -R -f docs/* gyc-hexo/source/_posts/
          cd gyc-hexo
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs(yuque): update posts from Yuque" || echo "No changes to commit"
          git push
