name: Deploy Yuque-Hexo Public To Pages

on:
  # 允许手动push触发
  push:
    branches:
      - main 
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@master

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
          
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: 安装Hexo并使用elog
        run: |
          export TZ='Asia/Shanghai'
          pnpm install --no-frozen-lockfile
          pnpm add -g @elog/cli    

      - name: 拉取语雀文章
        env:
          # 语雀相关环境变量
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
          ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 对应package.json中的script.sync
          elog sync

      - name: 更新时间并提交更改
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: 更新文档和时间戳" || echo "没有变更需要提交"
        env:
          PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

      - name: 推送文章到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
